language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
  access_key_id: AKIAIYB5P7QZSBFAFP6A
  secret_access_key:
    secure: q7MDiDk5uugABGd46fGvZI0NYjFLkmlCrit5LY3q9uTLAH/Gt1R9Foe8S+7GTYyMc4qCUER/52hZsfh6RMaJnEDSlps6i+mshCNLhdXUb7p2e3ncY5hUd/JN4JqaaozvhzHGmXy4Th9FFf9g2nEboB78sjkPyb+kr8uTNg5q+SVv1SXPmXBZBDrxqQC7x7rizkAdPd4b6FAb7fQtPqmoWQjN3s94cWpo6ot+vfRYX8b3IUKjLw2PqWfrXAECAYpF0VWAmGUF1b3atAcVAUyg9lBOl5dOVjYKSkxy7Ql1iJPIqn++fspAj/e5Czra/nvAG7WJ1BLtimXEpz84XugdO2XtIOx/NwYBOVQ1fC7QdL2J6OaXA/qdxAyvpcg/vDXy6Ci+i/Qs+YC2mCOfCSWNUU7EtqnkqBUXaG7UA3AsYEvw2XDtYgJv1HvyHWZvqbE3MHoLkd8f1Zzc3C0ubNvv+OYaMqvQ1zsIqnWo7aNS3yLm4OWqX6e1h5kRtwhScEK4/D4ijx07VgrudmkykORd8pZc+3vIfkA5VsXYY5vMAeyZTOchCwl0vFsQEbOyeQ8WPBbKXaO7mwhnie3cfOQ+pS9pxkpT9y74rYjkxZyGcenyh1YeencwNESaXD8yDXZRW89xUhMmHelxi/mPPfnMdEolo5NTlU8Sn55Cd29HmrI=
  bucket: devops-travis
  region: us-west-2
