language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
  access_key_id: AKIAIYB5P7QZSBFAFP6A
  secret_access_key:
    secure: jSpoLNUPWiX9zb8MW0HDlDrpVMndcKOo6f2RHE1qmj7wQwYOLK7Qt4/rMBCg0QQwPQkEiem1hIOrmifJdGyQiovyo6dgknLm9s5xgCSoHA0Jo7/BczgDIgVLvFRp0ktmoH3CxVcpL2Ej/fts0lpC7nmXqdhlCUKD9GuXTx1nKLDiPSDmtS5ZjNEzXdM44CCYAPrpP6fDkR/ESXxxkDvNlMRPc/Yz8UHx0FP//UYieZomt11wVes/6lmNjXI+GUTQahPgN/TCjzhXujHdmu/EjXRl0CSgp9gpQtA4f/b0y3BwFb0VSRSu6OOic9xH5RtpULYlSgNFrIpseJoFrlvjxkKCLDgW1LnXO5S9Ca3fzBf5q/0zAHA3gB26kBZxETyvAlxaO/5y9PZgeqjxchJdR5axwMUBSOMbU5lw5QKIvKzSPs+QQfrBEUBn8NhSkGdzaNcXIkNe0Hq2mIjRxX+ZN0vJmgYrDyAY9PE3b4DO3D4XNl33DLIY72FYmrYD07C3nxydSdNjeuucfAOGaD7SMj8rEWktBKz7pdQxM//Ze3knCsm51ThKNqp1UVdLQ8itHsjXf8TsTAFsL1mhqxjGJ8HRJER/QSaAJQye9MsMIanSlObQ5iGiKqtpQXS18h9Ikgb5O/c2/8PwwzLY9VISQXbmBPu4ODS2+taCnrUPp+w=
  bucket: devops-travis
  region: us-west-2
